/**
 * 渲染共享层：chrome 文案、字段标题、值形态、时长格式化。
 * @module dsh-trace-narrator/renderer/common
 */

import type { Lang } from '../config.ts'

export interface RendererChrome {
  docTitle: string
  summaryHeading: string
  rawAppendixHeading: string
  meta: {
    session: string
    timeRange: string
    duration: string
    events: string
    dropped: string
    turns: string
    schema: string
    redaction: string
    generated: string
  }
  truncatedNote: string
  bannerNoLlm: string
  bannerValidation: string
  footer: string
}

export function rendererChrome(lang: Lang): RendererChrome {
  if (lang === 'en') {
    return {
      docTitle: 'Session Trace Report',
      summaryHeading: 'Summary',
      rawAppendixHeading: 'Raw Output Appendix',
      meta: {
        session: 'Session', timeRange: 'Time range', duration: 'Duration', events: 'Events',
        dropped: 'Dropped/truncated', turns: 'Turns', schema: 'Schema', redaction: 'Redaction',
        generated: 'Generated at',
      },
      truncatedNote: ' (script truncated)',
      bannerNoLlm: '⚠️ No AI summary was generated (LLM unavailable or retries exhausted). This is a template-only report.',
      bannerValidation: '⚠️ The summary failed schema validation. The raw output is in the appendix.',
      footer: 'Generated by dsh-trace-narrator',
    }
  }
  return {
    docTitle: '会话轨迹报告',
    summaryHeading: '总结',
    rawAppendixHeading: '原始输出附录',
    meta: {
      session: '会话', timeRange: '时间范围', duration: '时长', events: '事件数',
      dropped: '截断/丢弃', turns: '轮数', schema: 'Schema', redaction: '脱敏强度',
      generated: '生成时间',
    },
    truncatedNote: '（剧本已截断）',
    bannerNoLlm: '⚠️ 未生成 AI 总结：LLM 不可用或重试耗尽。以下为纯模板报告。',
    bannerValidation: '⚠️ 总结未通过 schema 校验。原始输出见附录。',
    footer: '由 dsh-trace-narrator 生成',
  }
}

/** 内置 schema 字段 → 展示标题（自定义 schema 的未知字段回退为原始键名）。 */
const FIELD_TITLES: Record<string, { 'zh-CN': string; en: string }> = {
  title: { 'zh-CN': '标题', en: 'Title' },
  duration: { 'zh-CN': '时长', en: 'Duration' },
  summary: { 'zh-CN': '总结', en: 'Summary' },
  key_steps: { 'zh-CN': '关键步骤', en: 'Key Steps' },
  decisions: { 'zh-CN': '决策', en: 'Decisions' },
  outcomes: { 'zh-CN': '产出', en: 'Outcomes' },
  incident: { 'zh-CN': '事故', en: 'Incident' },
  timeline: { 'zh-CN': '时间线', en: 'Timeline' },
  root_cause: { 'zh-CN': '根因', en: 'Root Cause' },
  fix: { 'zh-CN': '修复', en: 'Fix' },
  lessons: { 'zh-CN': '经验教训', en: 'Lessons' },
  goal: { 'zh-CN': '目标', en: 'Goal' },
  prerequisites: { 'zh-CN': '前置条件', en: 'Prerequisites' },
  steps: { 'zh-CN': '步骤', en: 'Steps' },
  key_concepts: { 'zh-CN': '核心概念', en: 'Key Concepts' },
  pitfalls: { 'zh-CN': '常见坑', en: 'Pitfalls' },
  problem: { 'zh-CN': '问题', en: 'Problem' },
  investigation: { 'zh-CN': '排查过程', en: 'Investigation' },
  smoking_gun: { 'zh-CN': '决定性证据', en: 'Smoking Gun' },
  why_it_failed: { 'zh-CN': '失败原因', en: 'Why It Failed' },
  what: { 'zh-CN': '概要', en: 'What' },
  who: { 'zh-CN': '参与方', en: 'Who' },
  when: { 'zh-CN': '时间', en: 'When' },
  outcome: { 'zh-CN': '结果', en: 'Outcome' },
  next_actions: { 'zh-CN': '后续动作', en: 'Next Actions' },
}

export function renderFieldTitle(key: string, lang: Lang): string {
  // ja 与 chrome 策略一致：回退到 zh-CN。
  return FIELD_TITLES[key]?.[lang === 'en' ? 'en' : 'zh-CN'] ?? key
}

export type RenderedValue =
  | { kind: 'text'; text: string }
  | { kind: 'list'; items: string[] }
  | { kind: 'json'; json: string }

export function renderValue(value: unknown): RenderedValue {
  if (typeof value === 'string') return { kind: 'text', text: value }
  if (typeof value === 'number' || typeof value === 'boolean') return { kind: 'text', text: String(value) }
  if (Array.isArray(value) && value.every(item => typeof item === 'string')) {
    return { kind: 'list', items: value as string[] }
  }
  try {
    return { kind: 'json', json: JSON.stringify(value, null, 2) }
  } catch {
    return { kind: 'json', json: String(value) }
  }
}

/** 时长（毫秒）→ 人类可读；不足 1 秒显示为「<1 秒」。 */
export function formatDuration(startedAt: number | undefined, endedAt: number | undefined, lang: Lang): string | undefined {
  if (startedAt === undefined || endedAt === undefined || endedAt < startedAt) return undefined
  const ms = endedAt - startedAt
  const seconds = Math.max(1, Math.round(ms / 1000))
  if (lang === 'en') {
    if (seconds < 60) return seconds === 1 ? '1 second' : `${seconds} seconds`
    const minutes = Math.round(seconds / 60)
    return minutes === 1 ? '1 minute' : `${minutes} minutes`
  }
  if (seconds < 60) return `${seconds} 秒`
  return `${Math.round(seconds / 60)} 分钟`
}
